import json
import os
import re
from typing import Any, Callable, Dict, List, Optional, Tuple


def save_dictionary(mapping: Dict[str, Any], filename: str = "dictionary.json") -> None:
    """
    Save a dictionary to a JSON file with pretty-print formatting.
    """
    with open(filename, "w", encoding="utf-8") as file:
        json.dump(mapping, file, indent=4)


def load_dictionary(filename: str = "dictionary.json") -> Dict[str, Any]:
    """
    Load a dictionary from a JSON file.
    """
    with open(filename, "r", encoding="utf-8") as file:
        return json.load(file)


def force_json_extension(file_path: str) -> str:
    """
    Ensure the given file path has a .json extension.
    """
    base, _ = os.path.splitext(file_path)
    return f"{base}.json"


def find_tokens(text: str) -> List[str]:
    """
    Extract tokens from the input text using a regular expression pattern.
    The pattern captures LaTeX math brackets, words (with or without leading spaces),
    and standalone punctuation.
    """
    pattern = (
        r'([\n\r\t]|'                                   # match any actual newline, carriage return, or tab
        r'[ ]+[ ]|'                                     # match two or more spaces
        r'[ ]+\[|[ ]+\]|[ ]+\$\$|[ ]+\$|[ ]+\\\[|[ ]+\\\]|[ ]+\\\(|[ ]+\\\)|[ ]+\\|'
        r'\[|\]|\$\$|\$|\\\[|\\\]|\\\(|\\\)|\\|'        # match specific bracket tokens or a literal backslash
        r'[ \f\v]+[A-Za-z0-9]+|'                        # match leading whitespace (except newline) plus a word
        r'[A-Za-z0-9]+|'                                # match words
        r'[ \f\v]+[:;()!?+\-_*&^%#={}\'\"]+|'           # match punctuation or quotes preceeded by space
        r'[.,:;()!?+\-_*&^%#={}\'\"])'                  # match punctuation or quotes
    )
    tokens = re.findall(pattern, text)
    delimiter_tokens = {r"\[", r"\]", r"\(", r"\)", r"\\", "[", "]", "$", "$$"}
    return [token.strip() if token.strip() in delimiter_tokens else token for token in tokens]


def collect_unique_tokens(source_file: str) -> List[str]:
    """
    Return unique tokenizer tokens from a source file, preserving first appearance.
    """
    tokens: Dict[str, None] = {}
    with open(source_file, "r", encoding="utf-8") as file:
        for line in file:
            for token in find_tokens(line):
                tokens.setdefault(token, None)
    return list(tokens.keys())


def generate_tokenizer(mapping: Dict[str, str]) -> Callable[[str], List[Optional[str]]]:
    """
    Generate a tokenizer function using a direct mapping from tokens to codes.
    """
    def tokenizer(text: str) -> List[Optional[str]]:
        tokens = find_tokens(text)
        return [mapping.get(token, None) for token in tokens]
    return tokenizer


class MissingCode(object):

    def __init__(self, code):
        self.code = code

    def __repr__(self):
        return f"\033[94m<none:\033[90m{self.code}\033[94m>\033[0m"


def generate_detokenizer(reverse_mapping: Dict[str, str]) -> Callable[[List[str]], List[Optional[str]]]:
    """
    Generate a detokenizer function using a reverse mapping from codes to tokens.
    """
    def detokenizer(code_sequence: List[str]) -> List[Optional[str]]:
        return [reverse_mapping.get(code, MissingCode(code)) for code in code_sequence]
    return detokenizer


def load_tokenizer(source_file: str) -> Tuple[Callable[[str], List[Optional[str]]], Callable[[List[str]], List[Optional[str]]]]:
    """
    Load the tokenizer and detokenizer from a JSON file generated by a tokenizer builder.
    """
    token_mapping = load_dictionary(source_file)
    return generate_tokenizer(token_mapping["direct"]), generate_detokenizer(token_mapping["reverse"])
