import json
import os
import re
from typing import Any, Callable, Dict, List, Optional, Tuple


TOKEN_PATTERN = re.compile(
    r'([\n\r\t]|'
    r'[ ]+[ ]|'
    r'[ ]+\[|[ ]+\]|[ ]+\$\$|[ ]+\$|[ ]+\\\[|[ ]+\\\]|[ ]+\\\(|[ ]+\\\)|[ ]+\\|'
    r'\[|\]|\$\$|\$|\\\[|\\\]|\\\(|\\\)|\\|'
    r'[ \f\v]+[A-Za-z0-9]+|'
    r'[A-Za-z0-9]+|'
    r'[ \f\v]+[:;()!?+\-_*&^%#={}\'\"]+|'
    r'[.,:;()!?+\-_*&^%#={}\'\"])'
)


def _normalize_delimiter_token(token: str) -> str:
    delimiter_tokens = {r"\[", r"\]", r"\(", r"\)", r"\\", "[", "]", "$", "$$"}
    return token.strip() if token.strip() in delimiter_tokens else token


def save_dictionary(mapping: Dict[str, Any], filename: str = "dictionary.json") -> None:
    """
    Save a dictionary to a JSON file with pretty-print formatting.
    """
    with open(filename, "w", encoding="utf-8") as file:
        json.dump(mapping, file, indent=4)


def load_dictionary(filename: str = "dictionary.json") -> Dict[str, Any]:
    """
    Load a dictionary from a JSON file.
    """
    with open(filename, "r", encoding="utf-8") as file:
        return json.load(file)


def force_json_extension(file_path: str) -> str:
    """
    Ensure the given file path has a .json extension.
    """
    base, _ = os.path.splitext(file_path)
    return f"{base}.json"


def find_tokens(text: str, lossless: bool = False) -> List[str]:
    """
    Extract tokens from the input text using a regular expression pattern.
    The pattern captures LaTeX math brackets, words (with or without leading spaces),
    and standalone punctuation. With ``lossless=True``, each character that
    falls outside the pattern is emitted as a fallback token, preserving the
    original text exactly.
    """
    if not lossless:
        return [_normalize_delimiter_token(token) for token in TOKEN_PATTERN.findall(text)]

    tokens: List[str] = []
    cursor = 0
    for match in TOKEN_PATTERN.finditer(text):
        if match.start() > cursor:
            tokens.extend(text[cursor:match.start()])
        # Legacy mappings normalize a few delimiter forms. A lossless mapping
        # instead preserves the exact matched spelling and its spacing.
        tokens.append(match.group(0))
        cursor = match.end()
    if cursor < len(text):
        tokens.extend(text[cursor:])
    return tokens


def collect_unique_tokens(
    source_file: str,
    lossless_tokenization: bool = False,
) -> List[str]:
    """
    Return unique tokenizer tokens from a source file, preserving first appearance.
    """
    tokens: Dict[str, None] = {}
    with open(source_file, "r", encoding="utf-8") as file:
        for line in file:
            for token in find_tokens(line, lossless=lossless_tokenization):
                tokens.setdefault(token, None)
    return list(tokens.keys())


def generate_tokenizer(
    mapping: Dict[str, str],
    lossless_tokenization: bool = False,
) -> Callable[[str], List[Optional[str]]]:
    """
    Generate a tokenizer function using a direct mapping from tokens to codes.
    """
    def tokenizer(text: str) -> List[Optional[str]]:
        tokens = find_tokens(text, lossless=lossless_tokenization)
        return [mapping.get(token, None) for token in tokens]

    # Experimental runners use this frozen mapping to choose and record a
    # deterministic OOV fallback code. It remains the same callable API.
    tokenizer.direct_mapping = mapping
    tokenizer.lossless_tokenization = lossless_tokenization
    return tokenizer


class MissingCode(object):

    def __init__(self, code):
        self.code = code

    def __repr__(self):
        return f"\033[94m<none:\033[90m{self.code}\033[94m>\033[0m"


def generate_detokenizer(reverse_mapping: Dict[str, str]) -> Callable[[List[str]], List[Optional[str]]]:
    """
    Generate a detokenizer function using a reverse mapping from codes to tokens.
    """
    def detokenizer(code_sequence: List[str]) -> List[Optional[str]]:
        return [reverse_mapping.get(code, MissingCode(code)) for code in code_sequence]
    return detokenizer


def load_tokenizer(source_file: str) -> Tuple[Callable[[str], List[Optional[str]]], Callable[[List[str]], List[Optional[str]]]]:
    """
    Load the tokenizer and detokenizer from a JSON file generated by a tokenizer builder.
    """
    token_mapping = load_dictionary(source_file)
    tokenization_mode = token_mapping.get("metadata", {}).get(
        "tokenization_mode", "legacy"
    )
    if tokenization_mode not in {"legacy", "lossless"}:
        raise ValueError(
            f"Unknown tokenizer tokenization_mode {tokenization_mode!r} in {source_file}."
        )
    return (
        generate_tokenizer(
            token_mapping["direct"],
            lossless_tokenization=tokenization_mode == "lossless",
        ),
        generate_detokenizer(token_mapping["reverse"]),
    )


def load_atomic_lexical_tokenizer(
    source_file: str,
) -> Tuple[Callable[[str], List[Optional[str]]], Callable[[List[str]], List[Optional[str]]]]:
    """Load a frozen lexical mapping as contiguous, one-event token IDs.

    The lexical boundaries and source-coverage mode come from the existing ILM
    tokenizer JSON. Only the model-facing code changes: each vocabulary entry
    is assigned a single integer ID instead of its hierarchical coordinate
    code. This supplies a conventional atomic-token control.
    """
    token_mapping = load_dictionary(source_file)
    tokenization_mode = token_mapping.get("metadata", {}).get(
        "tokenization_mode", "legacy"
    )
    if tokenization_mode not in {"legacy", "lossless"}:
        raise ValueError(
            f"Unknown tokenizer tokenization_mode {tokenization_mode!r} in {source_file}."
        )

    lexical_tokens = list(token_mapping["direct"].keys())
    direct_mapping = {
        token: str(index) for index, token in enumerate(lexical_tokens)
    }
    reverse_mapping = {
        str(index): token for index, token in enumerate(lexical_tokens)
    }
    tokenizer = generate_tokenizer(
        direct_mapping,
        lossless_tokenization=tokenization_mode == "lossless",
    )
    tokenizer.atomic_lexical = True
    return tokenizer, generate_detokenizer(reverse_mapping)
